### ISSUE TITLE
Could the Email object be extended to return also attachments information

### ISSUE THREAD

**Issue by bbogdanov24** [pavkam/codeceptjs-testmailapp-helper#2]
**What am I trying to achieve?**
I want to check if a mail is received on a certain address using Testmail.app and if the received email contains the expected attachments.

**Issue**
Currently, helper does not support attachments in the Email object

**Suggestion**
Attachments property to be added to [the query](https://github.com/pavkam/codeceptjs-testmailapp-helper/blob/main/index.js#L188) used to retrieve the last mail in receiveEmails() function.
That way if the user needs attachments to be checked this would be possible since they will be part of the response data.

**Comment by pavkam** [comment]
Thanks for the issue @ednasutrin. I have exposed the attachments through the email object now. Published an update to `npm` as well. Let me know if any issues.

**Comment by bbogdanov24** [comment]
Thanks a lot for the quick reaction @pavkam ! 
I am already using the new version.
